--    alter table application_container_templates 
--        drop constraint FK_95k8v0bl4sn5lhrir2mtopa13;
--
--    alter table application_container_templates 
--        drop constraint FK_fqb3jea28wcv43wkpl7n5srm0;
--
--    alter table application_image_templates 
--        drop constraint FK_kqk1aa5kuxk4cut0u8dtomyt7;
--
--    alter table application_image_templates 
--        drop constraint FK_mkrfmxejbkn35xy9xpk0chvi3;
--
--    alter table container_template_links 
--        drop constraint FK_alyb88m50ap2tetxaw5e5h2qy;
--
--    alter table container_template_links 
--        drop constraint FK_dd36msmxjqqhym8ye7s53xmeh;
--
--    alter table image_template 
--        drop constraint FK_iya0ueqms4duc080e9uwv893p;
--
--    alter table image_template_file_copys 
--        drop constraint FK_kq6gl74bmusq6jepjj90ks6qp;
--
--    alter table image_template_file_copys 
--        drop constraint FK_kvl9a6qjq35tl1wdg3j9uqf3c;
--
--    alter table image_template_sql_files 
--        drop constraint FK_pxk2lnbm8dwvauw8b79e4lrjd;
--
--    alter table image_template_sql_files 
--        drop constraint FK_5igupac1or38667p9fy3et5e4;
--
--    alter table provision 
--        drop constraint FK_5nxn1nlg6e75cx1ok7as3deha;
--
--    alter table provision_provision_tasks 
--        drop constraint FK_24ea0vq400g7jk3mm3rauh5h8;
--
--    alter table provision_provision_tasks 
--        drop constraint FK_qk4rhuablxum5yfs5e44ibys2;
--
--    alter table provision_task 
--        drop constraint FK_ge4acy9wbiqe0fwx4vshr4qgs;
--
--    alter table provision_task_notifications 
--        drop constraint FK_jq591re37p0vnj9pad5y6wl36;
--
--    alter table provision_task_notifications 
--        drop constraint FK_p1m5ola2rng85bv43jkh0xwhl;

    drop table application if exists;

    drop table application_container_templates if exists;

    drop table application_image_templates if exists;

    drop table container_template if exists;

    drop table container_template_links if exists;

    drop table file if exists;

    drop table image_template if exists;

    drop table image_template_file_copys if exists;

    drop table image_template_sql_files if exists;

    drop table link if exists;

    drop table notification if exists;

    drop table provision if exists;

    drop table provision_provision_tasks if exists;

    drop table provision_task if exists;

    drop table provision_task_notifications if exists;

create table application (
    ID INTEGER generated by default as identity (start with 1) not null,
    UUID varchar(255),
    NAME varchar(255),
    DESCRIPTION varchar(255),
    VERSION varchar(255),
    TYPE integer DEFAULT 2 NOT NULL,
    INACTIVE BOOLEAN DEFAULT 0 NOT NULL,
    LOCK_VERSION INTEGER DEFAULT 1 NOT NULL,
	LAST_UPDATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	LAST_UPDATE_USER VARCHAR(255) DEFAULT 'SYSTEM' NOT NULL,
	CREATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	CREATE_USER VARCHAR(255) DEFAULT 'SYSTEM' NOT NULL,
    primary key (id)
);

    create table application_container_templates (
        application integer not null,
        container_templates integer not null
    );

    create table application_image_templates (
        application integer not null,
        image_templates integer not null,
        primary key (application, image_templates)
    );

    create table container_template (
        id integer generated by default as identity (start with 1),
        create_user varchar(255),
        CREATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
        last_update_user varchar(255),
        LAST_UPDATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
        lock_version integer not null,
        inactive boolean not null,
        uuid varchar(255),
        cluster_size integer not null,
        expose_ports boolean not null,
        image varchar(255),
        name varchar(255),
        primary key (id)
    );

    create table container_template_links (
        container_template integer not null,
        links integer not null
    );

    create table file (
        dtype varchar(31) not null,
        id integer generated by default as identity (start with 1),
        create_user varchar(255),
        CREATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
        last_update_user varchar(255),
        LAST_UPDATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
        lock_version integer not null,
        url varchar(255),
        archive boolean,
        destination varchar(255),
        name varchar(255),
        primary key (id)
    );

    create table image_template (
        dtype varchar(31) not null,
        id integer generated by default as identity (start with 1),
        create_user varchar(255),
        CREATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
        last_update_user varchar(255),
        LAST_UPDATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
        lock_version integer not null,
        inactive boolean not null,
        uuid varchar(255),
        image_id varchar(255),
        name varchar(255),
        tag varchar(255),
        db_name varchar(255),
        password varchar(255),
        username varchar(255),
        war integer,
        primary key (id)
    );

    create table image_template_file_copys (
        image_template integer not null,
        file_copys integer not null
    );

    create table image_template_sql_files (
        image_template integer not null,
        sql_files integer not null
    );

    create table link (
        id integer generated by default as identity (start with 1),
        create_user varchar(255),
        CREATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
        last_update_user varchar(255),
        LAST_UPDATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
        lock_version integer not null,
        alias varchar(255),
        name varchar(255),
        primary key (id)
    );

    create table notification (
        id integer generated by default as identity (start with 1),
        create_user varchar(255),
        CREATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
        last_update_user varchar(255),
        LAST_UPDATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
        lock_version integer not null,
        email varchar(255),
        primary key (id)
    );

    create table provision (
        id integer generated by default as identity (start with 1),
        create_user varchar(255),
        CREATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
        last_update_user varchar(255),
        LAST_UPDATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
        lock_version integer not null,
        inactive boolean not null,
        uuid varchar(255),
        description varchar(255),
        name varchar(255),
        application integer,
        primary key (id)
    );

    create table provision_provision_tasks (
        provision integer not null,
        provision_tasks integer not null
    );

    create table provision_task (
        id integer generated by default as identity (start with 1),
        create_user varchar(255),
        CREATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
        last_update_user varchar(255),
        LAST_UPDATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
        lock_version integer not null,
        inactive boolean not null,
        uuid varchar(255),
        ended TIMESTAMP,
        provision_task_status integer,
        provision_task_type integer,
        scheduled TIMESTAMP,
        started TIMESTAMP,
        provision integer,
        primary key (id)
    );

    create table provision_task_notifications (
        provision_task integer not null,
        notifications integer not null,
        primary key (provision_task, notifications)
    );

--    alter table application_container_templates 
--        add constraint UK_95k8v0bl4sn5lhrir2mtopa13  unique (container_templates);
--
--    alter table application_image_templates 
--        add constraint UK_kqk1aa5kuxk4cut0u8dtomyt7  unique (image_templates);
--
--    alter table container_template_links 
--        add constraint UK_alyb88m50ap2tetxaw5e5h2qy  unique (links);
--
--    alter table image_template_file_copys 
--        add constraint UK_kq6gl74bmusq6jepjj90ks6qp  unique (file_copys);
--
--    alter table image_template_sql_files 
--        add constraint UK_pxk2lnbm8dwvauw8b79e4lrjd  unique (sql_files);
--
--    alter table provision_provision_tasks 
--        add constraint UK_24ea0vq400g7jk3mm3rauh5h8  unique (provision_tasks);
--
--    alter table provision_task_notifications 
--        add constraint UK_jq591re37p0vnj9pad5y6wl36  unique (notifications);
--
--    alter table application_container_templates 
--        add constraint FK_95k8v0bl4sn5lhrir2mtopa13 
--        foreign key (container_templates) 
--        references container_template;
--
--    alter table application_container_templates 
--        add constraint FK_fqb3jea28wcv43wkpl7n5srm0 
--        foreign key (application) 
--        references application;
--
--    alter table application_image_templates 
--        add constraint FK_kqk1aa5kuxk4cut0u8dtomyt7 
--        foreign key (image_templates) 
--        references image_template;
--
--    alter table application_image_templates 
--        add constraint FK_mkrfmxejbkn35xy9xpk0chvi3 
--        foreign key (application) 
--        references application;
--
--    alter table container_template_links 
--        add constraint FK_alyb88m50ap2tetxaw5e5h2qy 
--        foreign key (links) 
--        references link;
--
--    alter table container_template_links 
--        add constraint FK_dd36msmxjqqhym8ye7s53xmeh 
--        foreign key (container_template) 
--        references container_template;
--
--    alter table image_template 
--        add constraint FK_iya0ueqms4duc080e9uwv893p 
--        foreign key (war) 
--        references file;
--
--    alter table image_template_file_copys 
--        add constraint FK_kq6gl74bmusq6jepjj90ks6qp 
--        foreign key (file_copys) 
--        references file;
--
--    alter table image_template_file_copys 
--        add constraint FK_kvl9a6qjq35tl1wdg3j9uqf3c 
--        foreign key (image_template) 
--        references image_template;
--
--    alter table image_template_sql_files 
--        add constraint FK_pxk2lnbm8dwvauw8b79e4lrjd 
--        foreign key (sql_files) 
--        references file;
--
--    alter table image_template_sql_files 
--        add constraint FK_5igupac1or38667p9fy3et5e4 
--        foreign key (image_template) 
--        references image_template;
--
--    alter table provision 
--        add constraint FK_5nxn1nlg6e75cx1ok7as3deha 
--        foreign key (application) 
--        references application;
--
--    alter table provision_provision_tasks 
--        add constraint FK_24ea0vq400g7jk3mm3rauh5h8 
--        foreign key (provision_tasks) 
--        references provision_task;
--
--    alter table provision_provision_tasks 
--        add constraint FK_qk4rhuablxum5yfs5e44ibys2 
--        foreign key (provision) 
--        references provision;
--
--    alter table provision_task 
--        add constraint FK_ge4acy9wbiqe0fwx4vshr4qgs 
--        foreign key (provision) 
--        references provision;
--
--    alter table provision_task_notifications 
--        add constraint FK_jq591re37p0vnj9pad5y6wl36 
--        foreign key (notifications) 
--        references notification;
--
--    alter table provision_task_notifications 
--        add constraint FK_p1m5ola2rng85bv43jkh0xwhl 
--        foreign key (provision_task) 
--        references provision_task;


-- just for testing
INSERT INTO APPLICATION(ID, NAME, VERSION) 
   VALUES(1, 'apache-test', '1.0');
